language: node_js

node_js:
  - 8

notifications:
  email:
    on_failure: change
    on_success: never

script:
  - npm run test -- -i
  - npm run build

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

after_success: 'npm run coveralls'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  CXX=g++-4.8

cache:
  npm: true
  directories:
    - node_modules
